services:
  ros2_rox:
    image: osrf/ros:humble-desktop
    container_name: ros2_rox_container
    tty: true
    privileged: true
    network_mode: host
    working_dir: /ros_ws
    environment:
      - ROS_DOMAIN_ID=0
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./ros_ws:/ros_ws
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    command: >
      bash -c "
        echo 'source /opt/ros/humble/setup.bash' >> ~/.bashrc &&
        apt-get update && apt-get upgrade -y &&
        apt-get install -y \
          git \
          vim \
          less \
          tree \
          fzf \
          fish &&
          exec bash
      "