version: '3.8'

services:
  ros2_rox:
    image: osrf/ros:humble-desktop
    container_name: ros2_rox_container
    privileged: true
    network_mode: host
    working_dir: /ros_ws
    environment:
      - ROS_DOMAIN_ID=0
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ~/ros_ws:/ros_ws
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: >
      bash -c "
      set -e &&
      echo 'Installing dependencies...' &&
      apt-get update -qq &&
      apt-get install -y -qq --no-install-recommends \
        python3-colcon-common-extensions \
        python3-rosdep \
        python3-vcstool \
        python3-pip \
        libcap-dev \
        libatlas-base-dev \
        libopenjp2-7 \
        libfmt-dev \
        libdrm-dev \
        python3-opencv \
        ros-humble-cv-bridge &&
      rm -rf /var/lib/apt/lists/*
      "


